apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    worker_processes auto;

    events {
      worker_connections 1024;
    }

    http {
      server {
        listen 80;

        location / {
          default_type  text/html;
          return 200 'Requested rout is: $request_uri\n';
        }
      }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'
          ports:
            - name: https
              containerPort: 443
            - name: http
              containerPort: 80
          volumeMounts:
            - name: nginx-conf-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-conf-volume
          configMap:
            name: nginx-conf

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
      name: http

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    # kubernetes.io/tls-acme: "true"
    # nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    # nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  name: nginx-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: nginx.prod16july1.humalect.dev
      http:
        paths:
          - backend:
              service:
                name: nginx-service
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - nginx.prod16july1.humalect.dev
      secretName: nginx-prod16july1-humalect-dev
